name: Build and Test

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]' ) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9, "3.10", 3.11]  # quoted 3.10 needed due to this bug: https://github.com/actions/runner/issues/1989

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Ruff Linting
        uses: chartboost/ruff-action@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install multidms
        run: |
            pip install --upgrade pip
            pip install -e ".[dev]"

      - name: Black Format Check
        run: |
            black --check .

      - name: Test
        run: |
          pytest
          pytest --doctest-modules

      - name: Test docs build
        run: |
          make -C docs clean
          make -C docs html