name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: 
      - main
      - gh_action_doc_test
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-20.04
    container: debian:buster
 
    steps:
        #- uses: actions/checkout@v3

    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git python3-pip
        apt upgrade python3-pip
        echo $(python --version)
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        git config --global --add safe.directory /__w/multidms/multidms
      shell: bash

      #- uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.9'

    - name: Install multidms
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
      shell: bash
      
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash
      
